# Generated by Django 2.0 on 2020-01-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('email_id', models.EmailField(max_length=40, unique=True)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('city', models.CharField(blank=True, max_length=10)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='female', max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Desinates whether this user should be considered active or not.', verbose_name='is_active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether this user is a member of staff to access the admin page or not', verbose_name='is_staff')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates whether this user has all permissions in the admin page or not', verbose_name='is_superuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
