# Generated by Django 2.0 on 2020-01-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20200106_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_id',
            field=models.EmailField(max_length=40, unique=True, verbose_name='Email ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Phone Number'),
        ),
    ]
