# Generated by Django 2.0 on 2020-01-08 06:34

import django.core.validators
from django.db import migrations, models
import user_app.validators.user_validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20200106_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(db_column='City', max_length=10, validators=[user_app.validators.user_validators.validate_city]),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, db_column='Date Joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(db_column='Date of Birth', help_text='date format should be YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_id',
            field=models.EmailField(db_column='Email ID', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(db_column='First Name', max_length=15, validators=[django.core.validators.MaxLengthValidator(limit_value=15), user_app.validators.user_validators.validate_first_name]),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], db_column='Gender', default='female', help_text='Choose either Female or Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(db_column='Last Name', max_length=30, validators=[django.core.validators.MaxLengthValidator(limit_value=20), user_app.validators.user_validators.validate_last_name]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='Password', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_column='Phone Number', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
