# Generated by Django 2.0 on 2020-01-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_auto_20200108_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desinates whether this user should be considered active or not.'),
        ),
    ]
