# Generated by Django 2.0 on 2020-01-08 07:12

from django.db import migrations, models
import sample_project.validators.user_validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_auto_20200108_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_column='Phone Number', max_length=13, primary_key=True, serialize=False, unique=True, validators=[
                sample_project.validators.user_validators.validate_phone_number]),
        ),
    ]
